import { StyleSheet } from "react-native";

export const comparadorStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F5F5F5",
    },
    body: {
        padding: 16,
        gap: 16,
        paddingBottom: 40,
    },

    headerWrap: {
        overflow: "hidden",
    },
    headerTopBar: {
        paddingHorizontal: 16,
        paddingTop: 14,
        paddingBottom: 6,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        zIndex: 10,
    },
    backCard: {
        backgroundColor: "#fff",
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 14,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 6,
        elevation: 4,
    },
    backCardLabel: {
        fontSize: 15,
        fontWeight: "700",
        color: "#1a1a2e",
    },
    headerVsLabel: {
        fontSize: 22,
        fontWeight: "900",
        color: "#fff",
        letterSpacing: 1,
        textShadowColor: "rgba(0,0,0,0.25)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 4,
    },
    headerPokemonRow: {
        flexDirection: "row",
        paddingHorizontal: 12,
        paddingBottom: 20,
        gap: 8,
    },
    headerPokemonCol: {
        flex: 1,
        alignItems: "center",
        gap: 4,
    },
    headerArtwork: {
        width: 100,
        height: 100,
    },
    headerPokeNumber: {
        fontSize: 11,
        fontWeight: "700",
        color: "rgba(255,255,255,0.75)",
    },
    headerPokeName: {
        fontSize: 16,
        fontWeight: "900",
        color: "#fff",
        textAlign: "center",
        textShadowColor: "rgba(0,0,0,0.2)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
    },
    headerTypeBadge: {
        paddingHorizontal: 10,
        paddingVertical: 3,
        borderRadius: 20,
        backgroundColor: "rgba(255,255,255,0.25)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.5)",
    },
    headerTypeLabel: {
        color: "#fff",
        fontSize: 9,
        fontWeight: "700",
    },
    headerTypeRow: {
        flexDirection: "row",
        gap: 4,
        flexWrap: "wrap",
        justifyContent: "center",
    },
    headerEmptySlot: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 24,
    },
    headerEmptyIcon: {
        fontSize: 32,
        opacity: 0.7,
    },
    headerEmptyLabel: {
        fontSize: 13,
        fontWeight: "700",
        color: "rgba(255,255,255,0.8)",
    },
    headerInputRow: {
        flexDirection: "row",
        gap: 6,
        width: "100%",
        paddingHorizontal: 4,
    },
    headerInput: {
        flex: 1,
        backgroundColor: "rgba(255,255,255,0.9)",
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 7,
        fontSize: 12,
        color: "#1a1a2e",
        fontWeight: "600",
    },
    headerBuscarBtn: {
        paddingHorizontal: 10,
        paddingVertical: 7,
        borderRadius: 10,
        backgroundColor: "rgba(0,0,0,0.25)",
        justifyContent: "center",
    },
    headerBuscarLabel: {
        color: "#fff",
        fontWeight: "800",
        fontSize: 11,
    },
    cambiarChipHeader: {
        backgroundColor: "rgba(255,255,255,0.25)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.5)",
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
    },
    cambiarChipLabel: {
        color: "#fff",
        fontSize: 10,
        fontWeight: "700",
    },

    vsText: {
        fontSize: 20,
        fontWeight: "900",
        color: "#1a1a2e",
        alignSelf: "center",
        marginTop: 8,
    },

    statsCard: {
        backgroundColor: "#fff",
        borderRadius: 20,
        padding: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 6,
        elevation: 3,
        gap: 12,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: "800",
        color: "#1a1a2e",
        letterSpacing: 0.3,
    },
    leyenda: {
        flexDirection: "row",
        gap: 16,
    },
    leyendaItem: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    leyendaDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    leyendaLabel: {
        fontSize: 12,
        fontWeight: "700",
        color: "#555",
    },
    statRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    statLabel: {
        fontSize: 12,
        fontWeight: "600",
        color: "#666",
        width: 70,
    },
    statBarsCol: {
        flex: 1,
        gap: 4,
    },
    barWrap: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    statVal: {
        fontSize: 11,
        fontWeight: "800",
        width: 36,
        textAlign: "right",
    },
    ganador: {
        fontWeight: "900",
    },
    barBg: {
        flex: 1,
        height: 7,
        backgroundColor: "#eee",
        borderRadius: 4,
        overflow: "hidden",
    },
    barFill: {
        height: "100%",
        borderRadius: 4,
    },
    totalRow: {
        gap: 8,
        marginTop: 4,
    },
    totalChip: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 12,
    },
    totalLabel: {
        color: "#fff",
        fontWeight: "800",
        fontSize: 13,
    },
    ganadorBanner: {
        backgroundColor: "#1a1a2e",
        paddingVertical: 12,
        borderRadius: 14,
        alignItems: "center",
    },
    ganadorText: {
        color: "#fff",
        fontWeight: "900",
        fontSize: 15,
        letterSpacing: 0.3,
    },

    hint: {
        alignItems: "center",
        padding: 24,
    },
    hintText: {
        color: "#aaa",
        fontSize: 14,
        textAlign: "center",
        lineHeight: 20,
    },

    header: { display: "none" },
    backBtn: { display: "none" },
    backLabel: { display: "none" },
    headerTitle: { display: "none" },
    selectoresRow: { display: "none" },
    selectorWrap: { display: "none" },
    selectorEmpty: { display: "none" },
    slotLabel: { display: "none" },
    inputRow: { display: "none" },
    selectorInput: { display: "none" },
    buscarBtn: { display: "none" },
    buscarBtnLabel: { display: "none" },
    selectorCard: { display: "none" },
    cambiarChip: { display: "none" },
    cambiarLabel: { display: "none" },
    selectorArtwork: { display: "none" },
    selectorNumber: { display: "none" },
    selectorName: { display: "none" },
    typeRow: { display: "none" },
    typeBadge: { display: "none" },
    typeLabel: { display: "none" },
    loadingLabel: { display: "none" },
    errorEmoji: { display: "none" },
    errorLabel: { display: "none" },
    resetBtn: { display: "none" },
    resetLabel: { display: "none" },
});